version: '3.8'
services:
  qdrant:
    container_name: qdrant
    image: $DOCKER_QDRANT
    restart: always
    expose:
      - '6333'
      - '6334'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/qdrant:/qdrant/storage:z
    environment:
      QDRANT__TELEMETRY_DISABLED: true
      # QDRANT__SERVICE__API_KEY: $QDRANT_API_TOKEN
  rmain:
    container_name: rmain
    image: $DOCKER_RMAIN
    restart: always
    expose:
      - '6381'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rmain:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6381", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  rdata:
    container_name: rdata
    image: $DOCKER_RDATA
    restart: always
    expose:
      - '6382'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6382", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  rcache:
    container_name: rcache
    image: $DOCKER_RCACHE
    restart: always
    expose:
      - '6383'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rcache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6383", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  worker:
    deploy:
      mode: replicated
      replicas: 2
    image: $DOCKER_WORKER
    depends_on:
      - rmain
      - rdata
      - rcache
    links:
      - rmain
      - rdata
      - rcache
    volumes:
      - ${WEBAPP_STORAGE_HOME}/smind_cache:/smind_cache
    healthcheck:
      test: ["CMD", "true"]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    container_name: api
    image: $DOCKER_API
    depends_on:
      - qdrant
      - rmain
      - rdata
      - rcache
    ports:
      - '8080:8080'
    environment:
      QDRANT_HOST: qdrant
      QDRANT_REST_PORT: 6333
      QDRANT_GRPC_PORT: 6334
      # QDRANT_API_KEY: $QDRANT_API_TOKEN
    links:
      - qdrant
      - rmain
      - rdata
      - rcache
    volumes:
      - ${WEBAPP_STORAGE_HOME}/smind_cache:/smind_cache
