version: '3.8'
services:
  wipe:
    container_name: wipe
    image: $DOCKER_WIPE
    pull_policy: always
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/smind_cache:/smind_cache
      - ${WEBAPP_STORAGE_HOME}/rbody:/rbody
      - ${WEBAPP_STORAGE_HOME}/rcache:/rcache
      - ${WEBAPP_STORAGE_HOME}/rdata:/rdata
      - ${WEBAPP_STORAGE_HOME}/rmain:/rmain
      - ${WEBAPP_STORAGE_HOME}/qdrant:/qdrant_data
# $DEV_LOCAL
