version: '3.8'
services:
  qdrant-1:
    container_name: qdrant-1
    image: $DOCKER_QDRANT
    restart: always
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ${WEBAPP_STORAGE_HOME}/qdrant_1:/qdrant_data
    environment:
      QDRANT__STORAGE__STORAGE_PATH: /qdrant_data/storage
      QDRANT__STORAGE__SNAPSHOTS_PATH: /qdrant_data/snapshots
      QDRANT__TELEMETRY_DISABLED: true
      QDRANT__CLUSTER__ENABLED: true
      QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS: 2000
    command: ["/bin/sh", "-c", "./qdrant --uri http://qdrant-1:6335"]
  qdrant-2:
    image: $DOCKER_QDRANT
    restart: always
    expose:
      - 6334
      - 6335
    volumes:
      - ${WEBAPP_STORAGE_HOME}/qdrant_2:/qdrant_data
    environment:
      QDRANT__STORAGE__STORAGE_PATH: /qdrant_data/storage
      QDRANT__STORAGE__SNAPSHOTS_PATH: /qdrant_data/snapshots
      QDRANT__TELEMETRY_DISABLED: true
      QDRANT__CLUSTER__ENABLED: true
      QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS: 2000
    command: ["/bin/sh", "-c", "sleep 10 && ./qdrant --bootstrap http://qdrant-1:6335"]
  qdrant-3:
    image: $DOCKER_QDRANT
    restart: always
    expose:
      - 6334
      - 6335
    volumes:
      - ${WEBAPP_STORAGE_HOME}/qdrant_3:/qdrant_data
    environment:
      QDRANT__STORAGE__STORAGE_PATH: /qdrant_data/storage
      QDRANT__STORAGE__SNAPSHOTS_PATH: /qdrant_data/snapshots
      QDRANT__TELEMETRY_DISABLED: true
      QDRANT__CLUSTER__ENABLED: true
      QDRANT__CLUSTER__CONSENSUS__TICK_PERIOD_MS: 2000
    command: ["/bin/sh", "-c", "sleep 10 && ./qdrant --bootstrap http://qdrant-1:6335"]
  rmain:
    container_name: rmain
    image: $DOCKER_RMAIN
    restart: always
    expose:
      - 6379
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rmain:/data
  rdata:
    container_name: rdata
    image: $DOCKER_RDATA
    restart: always
    expose:
      - 6379
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rdata:/data
  rcache:
    container_name: rcache
    image: $DOCKER_RCACHE
    restart: always
    expose:
      - 6379
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rcache:/data
  rbody:
    container_name: rbody
    image: $DOCKER_RBODY
    restart: always
    expose:
      - 6379
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rbody:/data
  worker-1:
    image: $DOCKER_WORKER
    restart: always
    expose:
      - 6380
    volumes:
      - ${WEBAPP_STORAGE_HOME}/smind_cache:/smind_cache
  worker-2:
    image: $DOCKER_WORKER
    restart: always
    expose:
      - 6380
    volumes:
      - ${WEBAPP_STORAGE_HOME}/smind_cache:/smind_cache
  api:
    image: $DOCKER_API
    restart: always
    ports:
      - '8080:8080'
    environment:
      QDRANT_HOST: qdrant-1
      QDRANT_REST_PORT: 6333
      QDRANT_GRPC_PORT: 6334
    volumes:
      - ${WEBAPP_STORAGE_HOME}/smind_cache:/smind_cache
# eof
