version: '3.8'
services:
  qdrant:
    container_name: qdrant
    image: $DOCKER_QDRANT
    restart: always
    expose:
      - '6333'
      - '6334'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/qdrant:/qdrant_data
    environment:
      QDRANT__STORAGE__STORAGE_PATH: /qdrant_data/storage
      QDRANT__STORAGE__SNAPSHOTS_PATH: /qdrant_data/snapshots
      QDRANT__TELEMETRY_DISABLED: true
      # QDRANT__SERVICE__API_KEY: $QDRANT_API_TOKEN
  rmain:
    container_name: rmain
    image: $DOCKER_RMAIN
    restart: always
    expose:
      - '6379'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rmain:/data
  rdata:
    container_name: rdata
    image: $DOCKER_RDATA
    restart: always
    expose:
      - '6379'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rdata:/data
  rcache:
    container_name: rcache
    image: $DOCKER_RCACHE
    restart: always
    expose:
      - '6379'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/rcache:/data
  worker:
    deploy:
      mode: replicated
      replicas: 2
    image: $DOCKER_WORKER
    depends_on:
      - rmain
      - rdata
      - rcache
    links:
      - rmain
      - rdata
      - rcache
    volumes:
      - ${WEBAPP_STORAGE_HOME}/smind_cache:/smind_cache
  api:
    container_name: api
    image: $DOCKER_API
    depends_on:
      - qdrant
      - rmain
      - rdata
      - rcache
    ports:
      - '8080:8080'
    environment:
      QDRANT_HOST: qdrant
      QDRANT_REST_PORT: 6333
      QDRANT_GRPC_PORT: 6334
      # QDRANT_API_KEY: $QDRANT_API_TOKEN
    links:
      - qdrant
      - rmain
      - rdata
      - rcache
    volumes:
      - ${WEBAPP_STORAGE_HOME}/smind_cache:/smind_cache
