version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    restart: always
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - /qdrant_storage:/qdrant/storage:z
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  api:
    container_name: quotes-api
    build:
      context: ./
      target: production
    image: quotes-api
    depends_on:
      - qdrant
      - cache
    ports:
      - 8080:8080
    environment:
      QDRANT_HOST: qdrant
      QDRANT_REST_PORT: 6333
      QDRANT_GRPC_PORT: 6334
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    links:
      - qdrant
      - cache
    volumes:
      - ./:/src
volumes:
  qdrant:
    driver: local
  cache:
    driver: local

# start_redis() {
#     pushd "$1"
#     redis-server "redis.conf" --port "$2" >> "redis.log" 2>&1 &
#     popd
# }

# start_redis rmain 6381 &
# start_redis rdata 6383 &
# start_redis rcache 6382 &
