version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    restart: always
    expose:
      - '6333'
      - '6334'
    volumes:
      - qdrant:/qdrant/storage:z
  rmain:
    image: $DOCKER_RMAIN
    restart: always
    expose:
      - '6381'
    volumes:
      - rmain:/data
  rdata:
    image: $DOCKER_RDATA
    restart: always
    expose:
      - '6382'
    volumes:
      - rdata:/data
  rcache:
    image: $DOCKER_RCACHE
    restart: always
    expose:
      - '6383'
    volumes:
      - rcache:/data
  worker:
    container_name: worker
    image: $DOCKER_WORKER
    depends_on:
      - rmain
      - rdata
      - rcache
    links:
      - rmain
      - rdata
      - rcache
    volumes:
      - smind_cache:/smind_cache
  api:
    container_name: api
    image: $DOCKER_API
    depends_on:
      - qdrant
      - worker
      - rmain
    ports:
      - '8080:8080'
    environment:
      QDRANT_HOST: qdrant
      QDRANT_REST_PORT: 6333
      QDRANT_GRPC_PORT: 6334
    links:
      - qdrant
      - rmain
    volumes:
      - smind_cache:/smind_cache
volumes:
  qdrant:
    driver: local
  rmain:
    driver: local
  rdata:
    driver: local
  rcache:
    driver: local
  smind_cache:
    driver: local
